version: '3'
services:
    #PHP Service
    backend-test:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend-test
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            -   ./:/var/www
